### ISSUE TITLE
TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by rudyxu1102** [yunchen132/nodeMysqlDemo#1]
```
D:\mysql\nodeMysqlDemo\app\dao\trendsDao.js:24
            connection.query($sql.queryAll,[],function (err,result) {
                      ^

TypeError: Cannot read property 'query' of undefined
    at D:\mysql\nodeMysqlDemo\app\dao\trendsDao.js:24:23
    at Handshake.onConnect [as _callback] (D:\mysql\nodeMysqlDemo\node_modules\mysql\
lib\Pool.js:58:9)
    at Handshake.Sequence.end (D:\mysql\nodeMysqlDemo\node_modules\mysql\lib\protocol
\sequences\Sequence.js:88:24)
    at Protocol.handleNetworkError (D:\mysql\nodeMysqlDemo\node_modules\mysql\lib\pro
tocol\Protocol.js:363:14)
    at PoolConnection.Connection._handleNetworkError (D:\mysql\nodeMysqlDemo\node_mod
ules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

这是为啥

**Comment by rudyxu1102** [comment]
刚学mysql，应该是没启动数据库，博主有空能否贴一下运行步骤

**Comment by cleverqin** [comment]
@FatDong1 根据的你的错误日志我初步判断应该是数据库链接的问题。你可以修改一下数据库链接的配置，如果有不懂得地方也可以查看msql模块的文档。

**Comment by rudyxu1102** [comment]
谢谢
